Update chaining-jobs.yml

diff --git a/.github/workflows/chaining-jobs.yml b/.github/workflows/chaining-jobs.yml
--- a/.github/workflows/chaining-jobs.yml
+++ b/.github/workflows/chaining-jobs.yml
@@ -18,6 +18,8 @@ jobs:
     steps:
       - name: Output for Job 1
         run: echo "Hello from Job 1. Run Job 3 equals ${{ github.event.inputs.run-job-3 }}"
+      - name: Make Job 2 Fail
+        run: exit 1 # everything that is not 0 makes it fail
 
   job-2:
     name: Job 2
